/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import chess.gui.GUI;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Controller controller = new Controller(new Board(), new GUI());
        controller.printBoard();
        //controller.move(new Pos(1,1), new Pos(2,1));
        controller.move(new Pos(1, 7), new Pos(2, 7));
        controller.printBoard();
    }
}
