/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import chess.gui.GUI;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Controller model = new Controller(new Board(), new GUI());
        model.printBoard();
    }
}
